// This file is auto-generated by uniffi, but we wrap it
// Import the generated bindings
import { NexusEngine as NativeNexusEngine } from 'nexus-engine';

export type Point = {
  x: number;
  y: number;
  pressure: number;
};

export type ColorPalette = {
  primary: string;
  secondary: string;
  accent: string;
  shades: string[];
};

class EngineWrapper {
  private engine: any;

  constructor() {
    this.engine = new NativeNexusEngine();
  }

  startStroke(id: number) {
    this.engine.start_stroke(id);
  }

  addPoint(id: number, point: Point) {
    this.engine.add_point(id, point);
  }

  finishStroke(id: number) {
    this.engine.finish_stroke(id);
  }

  applyTheme(palette: ColorPalette) {
    this.engine.apply_theme(palette);
  }

  getRecentStrokes(count: number) {
    return this.engine.get_recent_strokes(count);
  }

  undo() {
    this.engine.undo();
  }

  redo() {
    this.engine.redo();
  }

  setStabilizer(strength: number) {
    this.engine.set_stabilizer_strength(strength);
  }
}

export const NativeEngine = new EngineWrapper();
